# Base image
FROM python:3.8

# Set the working directory inside the container
WORKDIR /python

COPY ./python

RUN apt-get update && apt-get install -y python3 python3-pip

# Set environment variables, if necessary
# ENV MY_ENV_VAR=value

# Run the Flask application
CMD ["python", "python.py"]
