# Base image
FROM ubuntu

# Set the working directory inside the container
WORKDIR C:\Users\Nilesh satote\Desktop\CI-CD\programFile

# COPY python.py

RUN apt-get update && apt-get install -y python3 python3-pip

# Set environment variables, if necessary
# ENV MY_ENV_VAR=value

# Run the Flask application
CMD ["python", "python.py"]
